- lib/message.ex
- mix.exs
- notebooks/custom_functions.livemd
- notebooks/getting_started.livemd
- test/chains/data_extraction_chain_test.exs
- test/chains/llm_chain_test.exs
- test/chat_models/chat_open_ai_test.exs
- test/for_open_ai_api_test.exs
- test/utils_test.exs
- formatted files
- updated notebooks to use published release with Mix.install
> cleanup for release

- lib/chat_models/chat_open_ai.ex
This addresses #11 
Many ways to handle this, but using [Req.Request.put_header/3](https://hexdocs.pm/req/Req.Request.html#put_header/3) seemed to be the most sane approach.
Having said that, I can sense you are doing a bunch of development on the project @brainlid - so no offense if you need to reject it if it does not align with where you are going :)
If there is anything I can do to clean this up, please let me know.
> Adds support for setting the `OpenAI-Organization` header in requests

- CHANGELOG.md
- mix.exs
> prepare release v0.1.1

- lib/chat_models/chat_open_ai.ex
- test/chat_models/chat_open_ai_test.exs
- added test for expected response from streamed response body
- updated to use req streaming api
- detects Mint :closed error and does a retry which worked in local tests
May close #42?
> Use newer Req streaming API

- lib/chat_models/chat_open_ai.ex
- does a limited retry count of 3
- outputs a debug log
In my live testing, this fixes the issue with only 1 retry being taken.
> retry connection when underlying mint connection closed

- CHANGELOG.md
- lib/chains/routing_chain.ex
- lib/routing/prompt_route.ex
- test/chains/routing_chain_test.exs
- test/routing/prompt_route_test.exs
Resolves issue #74 
Makes it easier to use a RoutingChain when not needing an LLMChain as a result. We just need to know which route is selected.
> Breaking change to RoutingChain

- README.md
- lib/tools/calculator.ex
- test/tools/calculator_test.exs
- docs
- tests
- how a tool is called returning success/fail
- exception handling
> update calculator tool

- CHANGELOG.md
- lib/chat_models/chat_anthropic.ex
- lib/chat_models/chat_open_ai.ex
- lib/chat_models/llm_callbacks.ex
- test/chat_models/chat_anthropic_test.exs
- test/chat_models/chat_open_ai_test.exs
- LLM callbacks added
- Anthropic support added
- OpenAI support added
> support receiving rate limit info

- mix.exs
- mix.lock
Closes #122 
Thanks @MrYawe! I noticed your PR was merged and a new abacus release was published.
> upgrade abacus dep

- lib/chat_models/chat_ollama_ai.ex
Fairly new to your project I was having troubles getting ollama streaming to work. This fixed it for me.
> Fix ChatOllamaAI streaming response

- lib/chat_models/chat_anthropic.ex
- lib/utils/bedrock_config.ex
Adding documentation steps for using `ChatAnthropic` in AWS Bedrock.
> Documenting AWS Bedrock support with Anthropic Claude

- CHANGELOG.md
- lib/chains/data_extraction_chain.ex
- lib/chat_models/chat_ollama_ai.ex
- lib/message.ex
- lib/message/tool_call.ex
- mix.exs
- test/chains/data_extraction_chain_test.exs
- test/chains/llm_chain_test.exs
- test/chat_models/chat_mistral_ai_test.exs
- test/message/tool_call_test.exs
- update CHANGELOG
- formatter
- add new modules to docs outline
> Prepare for v0.3.0-rc.1

- lib/chains/llm_chain.ex
- lib/utils/chat_templates.ex
- mix.exs
- notebooks/bumblebee_llama3_1_json_tooluse.livemd
- test/chat_models/chat_open_ai_test.exs
- test/utils/chat_templates_test.exs
- test/utils/parser/llama3_1_custom_tool_paser_test.exs
- test/utils/parser/llama3_2_custom_tool_paser_test.exs
> prep for v0.3.0 release

- lib/chat_models/chat_open_ai.ex
- test/chat_models/chat_open_ai_test.exs
When an assistant message has text content AND tool calls, the generated data going back to OpenAI didn't include the tool calls.
This resulted in the following error from OpenAI: 
`Invalid parameter: messages with role "tool" must follow a preceding message with "tool_calls".`
Fixes issue #244
> fix issue with OpenAI converting a message to JSON

- lib/chat_models/chat_bumblebee.ex
- lib/utils/parser/llama3_1_custom_tool_paser.ex
- lib/utils/parser/llama3_2_custom_tool_paser.ex
- test/utils/parser/llama3_1_custom_tool_paser_test.exs
- test/utils/parser/llama3_2_custom_tool_paser_test.exs
Ensures consistent capitalization of library name.
> ensure consisten capitalization

- lib/chat_models/chat_mistral_ai.ex
- test/chat_models/chat_mistral_ai_test.exs
just really ported code over from ChatOpenAI as the implementations are similar.
> adds tool calls and usage for mistral ai.

- lib/chat_models/chat_open_ai.ex
Quick fix to enable correct verbose_api for OpenAi
> Fix OpenAI verbose_api

- lib/chat_models/chat_anthropic.ex
- test/chat_models/chat_anthropic_test.exs
Adds support for specifying multiple betas, similar to their official SDKs.
(I was playing with `token-efficient-tools-2025-02-19` and long context, and used this to add it)
> Support choice of Anthropic beta headers

- lib/chat_models/chat_google_ai.ex
- lib/message/content_part.ex
- test/chat_models/chat_google_ai_test.exs
- test/message/content_part_test.exs
Add support for file urls, according to https://ai.google.dev/api/files
> feat: File urls for Google

- lib/chains/llm_chain.ex
- test/chains/llm_chain_test.exs
Added `run_until_tool_used`.
The `run_until_tool_used/3` function makes it easy to instruct an LLM to use a
set of tools and then call a specific tool to present the results. This is
particularly useful for complex workflows where you want the LLM to perform
multiple operations and then finalize with a specific action.
This works well for receiving a final structured output after multiple tools
are used.
When the specified tool is successfully called, the chain stops processing and
returns the result. This prevents unnecessary additional LLM calls and
provides a clear termination point for your workflow.
> added LLMChain.run_until_tool_used/3

- lib/chat_models/chat_vertex_ai.ex
- test/chat_models/chat_vertex_ai_test.exs
update docs for vertex ai over how to pass api_key and file content
> Update docs for Vertex AI

- lib/message.ex
> simple formatting issue

- lib/chains/llm_chain.ex
- test/chains/llm_chain_test.exs
Refactored version of #331 with test coverage
Closes #331 
Closes #330
> filter out empty lists in message responses

- lib/chat_models/chat_anthropic.ex
- logs the full error response for more clarity
> expanded logging for ChatAnthropic API errors

- lib/chat_models/chat_google_ai.ex
Implemented changes based on the discussion in #351
> Add req_config to ChatMode.ChatGoogleAI

- CHANGELOG.md
- mix.exs
- test/chains/summarize_conversation_chain_test.exs
- test/chat_models/chat_anthropic_test.exs
> Prep for v0.4.o-rc.3

- CHANGELOG.md
- mix.exs
> Prepare for v0.4.0 release
