brainlid/langchain

test/chat_models/chat_open_ai_test.exs

Even when given specific instructions like `"Return the response 'Hi'."` ChatGPT (and LLMs in general) don't always follow the instructions *exactly* (for example, ChatGPT will often respond to the above prompt with `"Hi!"` - and the extra `!` makes the test fail).
As a result, equality testing on the response makes for flaky tests. This change keeps the test prompts, but instead matches on the responses with `=~`. Still not perfect, but less likely to be flaky, which in tests seems like a win.
@brainlid the other way to handle this problem is to just test on what's guaranteed by the API contract (i.e. just check the response is [string or null](https://platform.openai.com/docs/api-reference/chat/object) in the ChatGPT case). Up to you if you want to take that route instead.

make chatgpt response tests more robust

---

lib/chains/data_extraction_chain.ex

... This appears to be the only valid result at this stage.
I see no place where you would expect to receive a response with `role: :function_call` in the current implementation after calling `LLMChain.run()`.
Context here is #14 as I am able to reproduce the same error with the example in that issue as well as the example provided in the moduledoc for `LangChain.Chains.DataExtractionChain`.

Set pattern match in `DataExtractionChain` to look for `role: :assistant` rather than `role: :function_call`

---

lib/chains/data_extraction_chain.ex

Didn't consistently handle 'null' values. For missing values, it might provide a `0` or `""` value instead of `null` which becomes `nil` in Elixir.

improved the data extraction prompt

---

lib/chains/llm_chain.ex
test/chains/llm_chain_test.exs

- added tests
Makes it easy to update the LLMChain's attached `custom_context`. This is relevant because a Function may alter the data that was passed in through the context. A subsequent Function execution should receive the updated value in the `custom_context`.

add "update_custom_context" to LLMChain

---

lib/chat_models/chat_open_ai.ex
test/chat_models/chat_open_ai_test.exs

refactor(chat_open_ai): Harden `do_process_response`

---

lib/chat_models/chat_open_ai.ex
test/chat_models/chat_open_ai_test.exs

The new update to OpenAI ChatGPT APIs allow users to specify if they want their response to be in JSON or not (defaults to text). 
This allows Langchain to specify the response type as valid JSON or not.
https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format

Adds support for JSON mode in OpenAI Chat model

---

lib/chat_models/chat_open_ai.ex
lib/utils.ex
test/chains/data_extraction_chain_test.exs
test/chains/llm_chain_test.exs
test/chat_models/chat_open_ai_test.exs
test/tools/calculator_test.exs

- Fixed the live calculator test. Was broken.
- Added "seed" support for [OpenAI's Reproducible outputs](https://platform.openai.com/docs/guides/text-generation/reproducible-outputs). This reduces (doesn't guarantee) errors in `live_call` tests that run against ChatGPT because it would vary the output.

support openai seed - improves "live" test behavior

---

lib/chains/data_extraction_chain.ex
lib/function.ex
lib/function_param.ex
lib/utils.ex
test/chains/data_extraction_chain_test.exs
test/chat_models/chat_open_ai_test.exs
test/function_param_test.exs
test/function_test.exs
test/tools/calculator_test.exs

- helps define a function's parameters more easily
- more tests needed
closes #23

created FunctionParam struct

---

lib/chat_models/chat_open_ai.ex

[Due to the intermittent issues exposed by Finch disconnecting](https://github.com/brainlid/langchain/issues/42), this PR adds Req retry logic to API requests. 
Retries are attempted up to 3 times and trigger for all HTTP errors with a 1 second delay.
I figure a test wasn't required given the Req library tests this and I've just added in options to trigger it.

Add retry strategy to OpenAI Chat API requests

---

lib/utils/chain_result.ex
test/utils/chain_result_test.exs

- helper functions for working with an LLMChain's result value
- added `to_string/1` and `to_string!/1` function to return the assistant's response as a string. Returns error for various invalid cases.
- added `to_map/3` and `to_map!/3` function for writing the assistant's response to a map under a desired key.
- tests

added Utils.ChainResult module

---

lib/chat_models/chat_open_ai.ex
test/chat_models/chat_open_ai_test.exs

In this PR I'm suggesting an addition of api_key passing directly through the Chat interface. This is done to allow users of the library to dynamically pass api_key based on who is using the chat.
My personal use case is as following: 
I give my users possibility to pass their own OpenAI API_KEY through interface. Because of that I can't retrieve it from config. I have to inject it during the call.
In case I''ve missed anything in the PR I'm happy to improve it!
Thanks!

Add possibility to use api_key per chat invocation.

---

lib/chat_models/chat_open_ai.ex
test/chat_models/chat_open_ai_test.exs

Hello guys! 
I was testing this lib, when I came across the error `Unrecognized request argument supplied: api_key` that ChatGPT than returned when execute the `LLMChain.run`
So I looked deeper into what the problem was and discovered that this line bellow:
```elixir
def for_api(%ChatOpenAI{} = openai, messages, functions) do
%{
model: openai.model,
api_key: openai.api_key, # this line is not necessary, because this go into body request
temperature: openai.temperature,
frequency_penalty: openai.frequency_penalty,
n: openai.n,
stream: openai.stream,
messages: Enum.map(messages, &ForOpenAIApi.for_api/1),
response_format: set_response_format(openai)
}
|> Utils.conditionally_add_to_map(:seed, openai.seed)
|> Utils.conditionally_add_to_map(:functions, get_functions_for_api(functions))
end
``` …

Fix OpenAI returns "Unrecognized request argument supplied: api_key"

---

test/prompt_template_test.exs
test/tools/calculator_test.exs

* Uses `with_io` to capture warning output

Cleanup non-api test warning output

---

lib/chains/llm_chain.ex
lib/chat_models/chat_google_ai.ex
lib/chat_models/chat_model.ex
lib/chat_models/chat_open_ai.ex
lib/message.ex
lib/message_delta.ex
lib/utils.ex
test/chat_models/chat_google_ai_test.exs

This PR adds a `ChatGoogleAI` model that wraps interactions with the [Google AI Rest APIs](https://ai.google.dev/tutorials/rest_quickstart#multi-turn_conversations_chat) for the purposes of integrating with langchain, thus closing #6.
This change supports the full set of Gemini Pro features, including non-streamed responses, streamed responses and function calling.
- Google uses the `"model"` role instead of `"assistant`"
- Streaming chunks have an identical schema to single-shot messages. This allowed a lot of reuse of the message parsing code for both Messages and MessageDeltas.
- I implemented the `for_api/` behaviour using plain old pattern matching. The protocol appoach seems a little roundabout. 
- Google AI doesn't support system prompts at the moment. I asked in the Google Discord …

Add support for Google AI / Gemini Pro model

---

lib/chat_models/chat_ollama_ai.ex
test/chat_models/chat_ollama_ai_test.exs
test/test_helper.exs

Adds support for open source models with [Ollama](https://github.com/jmorganca/ollama) which allows the execution of LLM's locally. Per the current version of the [API](https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-chat-completion) it doesn't seem like function calling is supported yet. See [this issue](https://github.com/jmorganca/ollama/issues/1729) to track on the possible status of function calling
This issue should close https://github.com/brainlid/langchain/issues/67

Add support for Ollama open source models

---

lib/chains/llm_chain.ex

Adds a clause to match an `{:ok, Message.t()}` payload according to the [spec for the call function](https://github.com/brainlid/langchain/blob/main/lib/chat_models/chat_model.ex#L2)
Addresses #71

Add clause to match call_response spec

---

lib/chat_models/chat_open_ai.ex
test/chat_models/chat_open_ai_test.exs

One of the optional fields that the OpenAI Api allows for in chat completions is `max_tokens`.
https://platform.openai.com/docs/api-reference/chat/create#chat-create-max_tokens

Add max_tokens option for OpenAI calls

---

lib/chat_models/chat_mistral_ai.ex
test/chat_models/chat_mistral_ai_test.exs

This PR adds support for [Mistral API](https://docs.mistral.ai/api/) chat.

Add mistral chat

---

lib/chat_models/chat_google_ai.ex

[BUG][GOOGLEAI] : Invalid default url for google ai

---

lib/chat_models/chat_open_ai.ex

- sends it both ways
- Azure OpenAI requires an "api-key" header
- Standard OpenAI requires auth bearer header
- formatting

Azure OpenAI support: send the auth api key differently

---

lib/chat_models/chat_anthropic.ex
lib/utils.ex
test/chat_models/chat_anthropic_test.exs

- allow for a single message. Don't assume a list.
- added live full-stack tests to Anthropic

update Utils.fire_callback for Anthropic support

---

lib/chat_models/chat_bumblebee.ex
lib/utils/chat_templates.ex
test/utils/chat_templates_test.exs

Chat template and appropriate tests added.

Add llama-3 chat template

---

MODEL_BEHAVIORS.md
lib/chat_models/chat_open_ai.ex
lib/message/content_part.ex
mix.exs
test/chat_models/chat_open_ai_test.exs

Updated OpenAI to use ContentPart's media option for setting image media data when base64 encoded.

fix openai content part media

---

lib/chains/llm_chain.ex
lib/chat_models/chat_anthropic.ex
lib/chat_models/chat_open_ai.ex
lib/message/content_part.ex
lib/message/tool_call.ex
test/chat_models/chat_open_ai_test.exs
test/message/content_part_test.exs

Enhances support for more standard/accepted image types with ContentParts

Updates for ContentPart images with messages to support ChatGPT's "detail" level option

---

lib/images.ex
lib/images/generated_image.ex
lib/images/open_ai_image.ex
test/images/generated_image_test.exs
test/images/open_ai_image_test.exs
test/images_test.exs

This adds support for the OpenAI-specific API interface for generating images using DALL-E-2 and DALL-E-3.
It returns a `LangChain.Images.GeneratedImage` struct and LangChain.Images` module makes it easy to download generated images.

add openai image endpoint support (aka DALL-E-2 & DALL-E-3)

---

lib/chains/llm_chain.ex
lib/chat_models/chat_open_ai.ex
lib/message.ex
lib/prompt_template.ex
test/chains/llm_chain_test.exs
test/message_test.exs
test/prompt_template_test.exs

- added PromptTemplate.to_content_part!
- added error detection when trying to send PromptTemplates that aren't converted to messages
- convert them to ContentPart type text

allow PromptTemplates to convert to ContentParts

---

test/chat_models/chat_ollama_ai_test.exs

Fixes
```
warning: 0..-2 has a default step of -1, please write 0..-2//-1 instead
test/chat_models/chat_ollama_ai_test.exs:160: ChatModels.ChatOllamaAITest."test call/2 basic content example with streaming"/1
```

Fix elixir 1.17 warnings

---

CHANGELOG.md
lib/chains/llm_chain.ex
lib/chat_models/chat_anthropic.ex
lib/chat_models/chat_bumblebee.ex
lib/chat_models/chat_google_ai.ex
lib/chat_models/chat_mistral_ai.ex
lib/chat_models/chat_model.ex
lib/chat_models/chat_ollama_ai.ex
lib/chat_models/chat_open_ai.ex
lib/chat_models/chat_vertex_ai.ex
lib/images/open_ai_image.ex
lib/utils.ex
mix.exs
test/chains/llm_chain_test.exs
test/chat_models/chat_anthropic_test.exs
test/chat_models/chat_bumblebee_test.exs
test/chat_models/chat_google_ai_test.exs
test/chat_models/chat_mistral_ai_test.exs
test/chat_models/chat_model_test.exs
test/chat_models/chat_ollama_ai_test.exs
test/chat_models/chat_open_ai_test.exs
test/chat_models/chat_vertex_ai_test.exs
test/utils_test.exs

Major clean-up and updates. Test are all passing. There may be issues in some chat models that don't have good test coverage for non-live tests. This is why it's an RC! Plus docs update would be good.
functions for adding callbacks
- LLMChain supports adding a callback to it's model
- makes it easier when restoring a model via config or from a router and hooking up a callback chain
chat models support config serialization
- closes https://github.com/brainlid/langchain/discussions/104 discussion
- ChatModel top-level functions
- ChatOpenAI
- ChatAnthropic
- ChatBumblebee
- Utils functions
- ChatGoogleAI - added callback support (I think)
- ChatVertexAI
ollama updated for initial support of callbacks
- supports serializing
updated ChatMistralAI
- callbacks support
- new api
- serializing

Big update - RC ready

---

lib/message.ex

It fixes a minor typespec error on `Langchain.Message.new_user!/1`.
I'm working on a small project that does image analysis with AI and I am using this elixir package following the guidelines of [this notebook](https://github.com/brainlid/langchain/blob/main/notebooks/context-specific-image-descriptions.livemd) and I get an error when running `mix dialyzer`.
This notebook recommends building messages as follows:
```elixir
messages = [
Message.new_system!("""
...
System description
....
"""),
Message.new_user!([
PromptTemplate.from_template!("""
...
Template description
...
"""),
ContentPart.image!(image_data, media: :jpg, detail: "low")
])
]
```
This code actually works but the typespec is not compatible with it:
```elixir
defmodule Langchain.Message do
@type t :: %Message{}
@spec …
```

fix: typespec error on Message.new_user/1

---

mix.exs

Removing a leftover reference to `ApiOverride` after the switch to Mimic in https://github.com/brainlid/langchain/pull/155

Remove ApiOverride reference in mix.exs project.docs

---

lib/chat_models/chat_open_ai.ex
test/chat_models/chat_open_ai_test.exs

We recently noticed that chat streams would appear to "hang" in the middle of generating a response. After a bit of debugging I found that it was due to the message being split in the middle of the "data: " part (i.e. "dat" in the last message, then "a: {" in the next). This results in the stream failing to parse any future messages and appearing to "hang" or freeze.
Haven't seen this issue before so I'm guessing something has changed in the way OpenAI streams their responses.
I couldn't see any tests for this particular case in the official node & python clients, but I modified [one of the node clients tests](https://github.com/openai/openai-node/blob/master/tests/streaming.test.ts#L37-L38) to check and it is supported (still passes). The node client appears to [split by line …

Fix OpenAI chat stream hanging

---

lib/utils.ex
test/utils_test.exs

Trying out Azure OpenAI service and ran into an issue with streaming chat completions (`gpt-4o` version `2024-05-13`).
A case clause error occurs in `LLMChain.do_run` ([link](https://github.com/brainlid/langchain/blob/6fed31cc53ababe359b712be4bcf3c96e5ea2a9f/lib/chains/llm_chain.ex#L346)). The issue is a message is being transformed and returning `[]`.
```
16:20:35.537 [error] {{:case_clause, {:ok, [[], [%LangChain.MessageDelta{content: "", status: :incomplete, index: 0, role: :assistant, tool_calls: nil}], [%LangChain.MessageDelta{
```
The message from Azure OpenAI that results in a `[]` return value from `do_process_return` is (from [here](https://github.com/brainlid/langchain/blob/6fed31cc53ababe359b712be4bcf3c96e5ea2a9f/lib/chat_models/chat_open_ai.ex#L666-L668)):
```
%{
"choices" => …
```

Fix streaming error when using Azure OpenAI Service

---

lib/prompt_template.ex

This gave me an error because it doesn't match `%LangChain.Message{}`

Fix PromptTemplate example

---

lib/chat_models/chat_anthropic.ex
lib/message_delta.ex
test/chat_models/chat_anthropic_test.exs
test/message_delta_test.exs

- Fixes an issue where a streamed tool call from Anthropic was failing.
- MessageDelta tool_calls support "index" values not matching to the position.
- Added tests around the scenario.

Anthropic support for streamed tool calls with parameters

---

lib/chains/data_extraction_chain.ex
lib/chains/llm_chain.ex
lib/chains/text_to_title_chain.ex
lib/chat_models/llm_callbacks.ex
lib/utils/chain_result.ex
notebooks/context-specific-image-descriptions.livemd
notebooks/custom_functions.livemd
notebooks/getting_started.livemd
test/chains/data_extraction_chain_test.exs
test/chains/llm_chain_test.exs
test/chains/routing_chain_test.exs
test/chains/text_to_title_chain_test.exs
test/chat_models/chat_anthropic_test.exs
test/chat_models/chat_google_ai_test.exs
test/tools/calculator_test.exs
test/utils/chain_result_test.exs

- Remove the "last_message" from the return tuple of `LLMChain.run/2`
- Data is still available in `%LLMChain{last_message: last_message}`
- Adds `%LLMChain{exchanged_messages: exchanged_messages}`.
This is a breaking change. Let's cover why this is being done and how to adapt to it.
Before this change, an `LLMChain`'s `run` function returned `{:ok, updated_chain, last_message}`. 
When an assistant (ie LLM) issues a ToolCall and when `run` is in the mode `:until_success` or `:while_need_response`, the `LLMChain` will automatically execute the function and return the result as a new Message back to the LLM. This works great!
The problem comes when an application needs to keep track of all the messages being exchanged during a run operation. That can be done by using callbacks and sending …

change return of LLMChain.run/2 - breaking change

---

lib/message/tool_call.ex
lib/message_delta.ex
test/chat_models/chat_open_ai_test.exs
test/message/tool_call_test.exs
test/message_delta_test.exs

Before this fix, tool call arguments in deltas which contained several empty spaces were missing data when being cast.
While triaging this issue I also added some extra tests checking for correct casting of spaces.

🐛 cast tool_calls arguments correctly inside message_deltas

---

lib/message/tool_call.ex
test/message/tool_call_test.exs

When using streaming with tools in ChatGoogleAI I've noticed that the merge method in tool_calls duplicated the name of the function. 
Because of that the tool calls were not working. For some reason ChatGoogleAI sends the same message delta with tools twice.
Below you can see that the name of the function was being duplicated: `image_1__generate_image` converted into `image_1__generate_imageimage_1__generate_image`.
```
primary: %LangChain.MessageDelta{
content: nil,
status: :complete,
index: 0,
role: :assistant,
tool_calls: [
%LangChain.Message.ToolCall{
status: :incomplete,
type: :function,
call_id: "call-image_1__generate_image",
name: "image_1__generate_image",
arguments: %{"prompt" => "a dog"},
index: nil
}
]
}
delta call: %LangChain.Message.ToolCall{
status: :incomplete,
type: …
```

Do not duplicate tool call parameters if they are identical

---

lib/function.ex

https://platform.openai.com/docs/guides/function-calling
> When you enable Structured Outputs by supplying strict: true, the OpenAI API will pre-process your supplied schema on your first request, and then use this artifact to constrain the model to your schema.

Structured Outputs by supplying `strict: true`

---

lib/chat_models/chat_open_ai.ex
test/chains/data_extraction_chain_test.exs
test/chat_models/chat_open_ai_test.exs
test/message_delta_test.exs
test/support/fixtures.ex
test/test_helper.exs

This pull request introduces a new `json_schema` field to the `ChatOpenAI` module, which enhances the response format handling capabilities by allowing for JSON Schema-based validation.
1. **Field Definition**:
- Added `field :json_schema, :map, default: nil` to the `ChatOpenAI` struct.
- Updated the list of valid struct keys to include `:json_schema`.
2. **Response Format Handling**:
- Modified the `set_response_format` function to account for cases when `json_response` is true and `json_schema` is provided.
- If `json_response` is true and `json_schema` is not nil, the response format is set to include `json_schema`.
- If `json_response` is true but `json_schema` is nil, the response format defaults to `json_object`.
- If `json_response` is false, the response format is set to `text`. …

feat: add OpenAI's new structured output API

---

lib/chat_models/chat_anthropic.ex
lib/chat_models/chat_google_ai.ex
lib/utils.ex
test/chat_models/chat_anthropic_test.exs
test/chat_models/chat_google_ai_test.exs
test/utils_test.exs

The Google AI API now supports system instructions - https://ai.google.dev/gemini-api/docs/system-instructions?lang=rest
I've extracted the split_system_message function from ChatAnthropic and then handled processing the system message in the same way.

Support system instructions for Google AI

---

lib/chat_models/chat_google_ai.ex
test/chat_models/chat_google_ai_test.exs

When using a newer model variant such as `gemini-1.5-pro-002`, we occasionally receive empty text parts in the response, which was causing the validation of `ContentPart`s to fail. 
This PR filters those before creating the content part.

Handle empty text parts from GoogleAI responses

---

lib/chat_models/chat_google_ai.ex

Very sporadically, we see errors due to the usageMetadata map missing one of the token count fields when using the Google AI API.
This PR provides a fallback value when fetching either of the fields.

Handle missing token usage fields for Google AI

---

lib/chat_models/chat_google_ai.ex
test/chat_models/chat_google_ai_test.exs

If a function is defined with an empty parameter list, the API returns `* GenerateContentRequest.tools[0].function_declarations[0].parameters.properties: should be non-empty for OBJECT type\n` with the current implementation.
Removing the parameters key from the function declaration when there are no parameters resolves this.

Handle functions with no parameters for Google AI

---

lib/chat_models/chat_google_ai.ex

In addition to the STOP and SAFETY finish reasons, the Gemini API also returns a [number of others](https://ai.google.dev/api/generate-content#FinishReason).
This PR extracts a function along similar lines to `ChatAnthropic.stop_reason_to_status/1`, and then handles the additional statuses that can be returned.

Handle all possible finishReasons for ChatGoogleAI

---

lib/chat_models/chat_google_ai.ex

This code iterated over parts in the response, but the result was never used, as text_content was captured above and used instead.

Remove unused assignment from ChatGoogleAI

---

lib/chat_models/chat_google_ai.ex
test/chat_models/chat_google_ai_test.exs

This implements a new field on ChatGoogleAI for setting the safety settings for content filtering, following the documentation at https://ai.google.dev/gemini-api/docs/safety-settings#web and https://ai.google.dev/api/generate-content#v1beta.SafetySetting
Based on your comment at https://github.com/brainlid/langchain/pull/142#issuecomment-2183694933 I kept this as a simple list of maps, rather than introducing a struct and associated changesets, on the basis that the LLM will validate the settings.
I've added support for serializing the config, which should be backwards compatible as deserializing maps without the safety settings field will construct a model with the safety settings set to an empty list, which then wouldn't be added to the request as the list is empty.

Add support for passing safety settings to Google AI

---

lib/chains/text_to_title_chain.ex
test/chains/text_to_title_chain_test.exs

- added module doc with examples
- support providing examples for consistency
closes #163

add support for examples to title chain

---

lib/chains/llm_chain.ex
lib/function.ex
lib/message.ex
lib/message/tool_result.ex
lib/message_processors/json_processor.ex
test/chains/llm_chain_test.exs

This allows an Elixir function executed by an LLM through a `LangChain.Message.ToolCall` and `LangChain.Function` definition to return and store the raw Elixir data structure in the matching `LangChain.Message.ToolResult`.
An Elixir function can return a 3-item tuple like this:
```elixir
{:ok, "llm result text", raw_result}
```
Where the `elixir_data_to_keep` is assigned to the `%ToolResult{processed_content: raw_result}`.
- documentation updates
- `LLMChain.execute_tool_call` supports Elixir functions returning a 3-item tuple with the raw result

add "processed_content" to ToolResult struct and support storing Elixir data from function results

---

lib/chains/data_extraction_chain.ex
lib/chains/llm_chain.ex
lib/chains/routing_chain.ex
lib/chains/text_to_title_chain.ex
lib/chat_models/chat_anthropic.ex
lib/chat_models/chat_bumblebee.ex
lib/chat_models/chat_google_ai.ex
lib/chat_models/chat_mistral_ai.ex
lib/chat_models/chat_model.ex
lib/chat_models/chat_ollama_ai.ex
lib/chat_models/chat_open_ai.ex
lib/chat_models/chat_vertex_ai.ex
lib/langchain_error.ex
lib/message.ex
lib/utils/chain_result.ex
test/chains/llm_chain_test.exs
test/chat_models/chat_anthropic_test.exs
test/chat_models/chat_google_ai_test.exs
test/chat_models/chat_mistral_ai_test.exs
test/chat_models/chat_open_ai_test.exs
test/chat_models/chat_vertex_ai_test.exs
test/langchain_error_test.exs
test/utils/chain_result_test.exs

This is a major change to how errors are handled. Instead of `LLMChain.run` returning `{:error, updated_chain, string_error}`, it now returns `{:error, updated_chain, %LangChainError{}}`.
LangChainError has a `message`, which is the original string message being returned before. However, it now also has a `type` which is a string code like "invalid_json", "overload_error", "changeset", "unexpected_response", "timeout", "retries_exceeded", etc.
This makes it easier to detect an error type and take corrective action.
This is a big change that touches all the Chat models. I tested all I could. 
**What is incomplete:**
- I'm sure I missed some documentation updates
- Some Chat models either don't have live tests, or I'm not setup for testing them.
**What you need to do:**
- Check you …

Revamped error handling and handles Anthropic's "overload_error"

---

lib/chains/llm_chain.ex
test/chains/llm_chain_test.exs

- in `LLMChain.apply_delta/2`, an error tuple can be returned as a delta because that's how it was received. 
- When we receive an error where the server reports "overloaded", cancel the current delta.
Related to issue #193

Cancel a message delta when we receive "overloaded" error

---

lib/chains/llm_chain.ex
lib/langchain_error.ex
lib/utils.ex
test/chains/llm_chain_test.exs
test/utils_test.exs

- adds :with_fallbacks option to LLMChain.run/2 options
- adds :before_fallback function for chain modification
Fallbacks is a feature inspired by [fallbacks in the OG LangChain](https://python.langchain.com/docs/how_to/fallbacks/). 
It's an important feature for taking an LLM system into production. When a system like OpenAI goes down or rate limits your usage, this enables you to automatically fallback to a different LLM.
I think it works best going from OpenAI -> Azure OpenAI, or Anthropic -> Bedrock Anthropic. That's where the most similar behavior can be found.
Provides an alternate recovery option for Anthropic "overloaded" errors. Issue #193

implement initial support for fallbacks

---

lib/chat_models/chat_google_ai.ex
lib/message_processors/json_processor.ex
notebooks/context-specific-image-descriptions.livemd
test/chat_models/chat_google_ai_test.exs

It also makes the JSON response parsing in the image processing notebook more robust by including explicit regex to strip json-with-trip-quotes from the beginning and the end of the model output, which seems to be a popular way across different LLMs to return a requested JSON.
Fix #209, fix #208.

Fix content-part encoding and decoding for Google API.

---

README.md
lib/chains/llm_chain.ex
lib/chains/routing_chain.ex
lib/chat_models/chat_anthropic.ex
lib/langchain_error.ex
lib/prompt_template.ex
lib/utils/chain_result.ex
lib/utils/chat_templates.ex

Hi, and thanks for creating LangChain - it's a very useful library!
Apologies for unsolicited PR, but I decided to fix some low-hanging spec errors that dialyzer was complaining about, and also fixed `README.md` to use the new return type for `LLMChain.run()`. 
There are still a few dialyzer errors left but they are a bit more cryptic.
Hope that works!

Fix specs and examples

---

lib/chains/summarize_conversation_chain.ex
test/chains/summarize_conversation_chain_test.exs

Adds support for greater customization of behavior with `LangChain.Chains.SummarizeConversationChain` by allowing the set of messages used by the summarizing chain to be completely controlled.
Some LLM's behavior may greatly improve with this level of explicit control.

add explicit message support in summarizer

---

lib/tools/calculator.ex
mix.exs

This PR resolves #24.
`abacus` can't be compiled in livebook.
```
==> abacus
warning: in order to compile .yrl files, you must add "compilers: [:yecc] ++ Mix.compilers()" to the "def project" section of abacus's mix.exs
warning: in order to compile .xrl files, you must add "compilers: [:leex] ++ Mix.compilers()" to the "def project" section of abacus's mix.exs
Compiling 3 files (.erl)
src/new_parser.yrl:54:7: syntax error before: 'else'
%   54|       {'else', '$5'}
%     |       ^
src/new_parser.erl:819:13: function yeccpars2_46_/1 undefined
%  819|  NewStack = yeccpars2_46_(Stack),
%     |             ^
src/new_parser.yrl:71:2: inlined function yeccpars2_46_/1 undefined
%   71| expr -> expr '/' expr : {'/', [], ['$1', '$3']}.
%     |  ^
could not compile dependency :abacus, "mix compile" …
```

Change abacus to optional dep

---

lib/utils/chat_templates.ex
test/utils/chat_templates_test.exs

I'm doing something a bit funky and I need to be able to have messages in whatever order. 
eg system/user/assistant/user1/user2/assistant/user2/user1/assistant/etc.
The LLM (Ollama) doesn't seem to mind.

Remove constraint of alternating user, assistant

---

lib/chat_models/chat_ollama_ai.ex

Tried to use this with fly.io. I was unable to connection to Ollama hosted on a private flycast address. Enabling ipv6 fixed the issue.

feat: Enable :inet6 for Req.new for Ollama

---

lib/chat_models/chat_bumblebee.ex
lib/utils/chat_templates.ex

This commit adds the Prompt template for the Phi-4 model.
Tested with quantized Phi-4 on 40GB A100. (17.7 GB vram and 100GB ram to quantize)
template_format: :phi_4
If I should add the livebook let me know?

Add Bumblebee Phi-4

---

lib/utils/chat_templates.ex
test/utils/chat_templates_test.exs

I want to work with [Phi-4](https://huggingface.co/microsoft/phi-4) which has a slightly different chat template than previous versions.
I could add the template but I figured some time ago it would be practical to be able to pass a callback to `apply_chat_template!/3`.
This way, users don't have to wait for an release to use a new template.
So, here is a PR.
I might go ahead and add the `phi-4` template in a separate PR.

feat: apply chat template from callback

---

lib/chat_models/chat_google_ai.ex
lib/chat_models/chat_mistral_ai.ex
lib/chat_models/chat_ollama_ai.ex
lib/chat_models/chat_open_ai.ex
lib/chat_models/chat_vertex_ai.ex
test/chat_models/chat_open_ai_test.exs

- adds new "reasoning_mode". Sends "developer" role instead of "system" role.
- adds support for "reasoning_effort" API option
- refactors many of the for_api functions to include the model. The reasoning model changes how things are sent
Resolves issue https://github.com/brainlid/langchain/issues/232
I don't have [Tier 5](https://platform.openai.com/docs/guides/rate-limits#usage-tiers) usage so I can't live-test this on an `o1` model. It _should_ work as far as I can tell.

support for o1 OpenAI model

---

lib/chat_models/chat_ollama_ai.ex
test/chat_models/chat_ollama_ai_test.exs

This API parameter should keep the model "warm" in memory. Otherwise after 5 minutes it is unloaded, and can be expensive to re-load.
Relevant docs: https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately

feat: Support for Ollama keep_alive API parameter

---

lib/chat_models/chat_anthropic.ex
lib/chat_models/chat_bumblebee.ex
lib/chat_models/chat_google_ai.ex
lib/chat_models/chat_open_ai.ex
lib/token_usage.ex
test/token_usage_test.exs

Add raw field to TokenUsage

---

README.md
lib/chat_models/chat_open_ai.ex

Their OpenAI API support is more picky and doesn't fully support the OpenAI API. This loosens the config to maintain support with OpenAI but allow for use with LMStudio.
Closes #224

support LMStudio when using ChatOpenAI

---

lib/callbacks.ex
lib/chains/llm_chain.ex
lib/function.ex
lib/langchain_error.ex
test/callbacks_test.exs
test/chains/llm_chain_test.exs
test/function_test.exs

Hi! In upgrading some code to 0.3.0 I had a few exceptions to track down and found the lack of context in the caught error messages slowed things down.
This change adds context  to the error messages logged and kept in the chain for LLM functions and function callbacks. I took an initial stab at the places this seems most valuable while avoiding putting full stack traces in the chain. 
The details:
- caught exceptions were logging their type and message, however, without a stack trace or location for the exception debugging was required to locate some issues. 
- added format_exception/3 to LangChain.LangChainError to format exceptions with context from the stacktrace. The third argument is the format - :short only includes the location and the default gives a full stack trace at the end …

Include stacktrace context in messages for caught exceptions from LLM functions & function callbacks.

---

lib/chains/llm_chain.ex
test/chains/llm_chain_test.exs

When a Tool response message is created, it already fired an `on_tool_response_created`, but it now also fires the more general `on_message_processed`, because a tool result can certainly be considered being processed.
Related to discussion in #244

add on_message_processed callback when tool response is created

---

README.md

Move the `to_string` call into the pipeline as it returns a Tuple which IO.puts can't handle:
```log
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:ok, "The hairbrush is located in the drawer."} of type Tuple
```
Renamed the variable for consistency/compilation.

typos: Update Example for Syntax Issues

---

lib/chat_models/chat_ollama_ai.ex
test/chat_models/chat_ollama_ai_test.exs
test/test_helper.exs

Adds basic support for tools with ollama `v0.3`, tested with the hairbrush example:
```elixir
alias LangChain.Function
alias LangChain.Message
alias LangChain.Chains.LLMChain
alias LangChain.ChatModels.ChatOllamaAI
custom_context = %{
"user_id" => 123,
"hairbrush" => "drawer",
"dog" => "backyard",
"sandwich" => "kitchen"
}
custom_fn =
Function.new!(%{
name: "custom",
description: "Returns the location of the requested element or item.",
parameters_schema: %{
type: "object",
properties: %{
thing: %{
type: "string",
description: "The thing whose location is being requested."
}
},
required: ["thing"]
},
function: fn %{"thing" => thing} = _arguments, context ->
{:ok, context[thing]}
end
})
{:ok, updated_chain, %Message{} = message} =
LLMChain.new!(%{
llm: ChatOllamaAI.new!(%{model: …
```

Enable tool support for ollama

---

lib/chat_models/chat_anthropic.ex
lib/chat_models/chat_google_ai.ex
lib/chat_models/chat_mistral_ai.ex
lib/chat_models/chat_open_ai.ex
lib/chat_models/chat_vertex_ai.ex
lib/images/open_ai_image.ex
test/chat_models/chat_anthropic_test.exs
test/chat_models/chat_google_ai_test.exs
test/chat_models/chat_mistral_ai_test.exs
test/chat_models/chat_open_ai_test.exs
test/chat_models/chat_vertex_ai_test.exs
test/images/open_ai_image_test.exs

- **Problem:**
If we inspect some models with API key, its possible to log and expose this sensitive data.
- **Fix:**
Add a redact option on each sensitive field as described in [ecto doc](https://hexdocs.pm/ecto/Ecto.Schema.html#module-redacting-fields)

Redact api-key from models

---

lib/chat_models/chat_anthropic.ex
lib/message/tool_result.ex
test/chat_models/chat_anthropic_test.exs

Anthropic supports the `"cache_control" => %{"type" => "ephemeral"}` block for anything under the content blocks in `messages.content` (based on [docs](https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching#what-can-be-cached)).
Looks like currently only the text content in https://github.com/brainlid/langchain/blob/38e957d2985b054ce51e087b51bb1af54aee9754/lib/chat_models/chat_anthropic.ex#L872-L881 was supported
This adds the options keyword similar to how ContentPart implements it, to allow setting a tool result to be cached or not.

Support caching tool results for Anthropic calls

---

lib/chat_models/chat_open_ai.ex
lib/message/content_part.ex
test/chat_models/chat_open_ai_test.exs
test/message/content_part_test.exs

OpenAI [now supports PDF files as input](https://platform.openai.com/docs/guides/pdf-files?api-mode=chat&utm_source=alphasigna), either as Base64-encoded data or as file IDs obtained after uploading files to the `/v1/files` endpoint.
This PR adds support for pdf content as Base64-encoded data.

feat: add support for pdf content with OpenAI model

---

lib/chat_models/chat_google_ai.ex
test/chat_models/chat_google_ai_test.exs

This PR introduces support for the json_response option in `ChatModels.ChatGoogleAI`. With this update, users can now enable JSON response formatting by setting `json_response` to true. When enabled, the API request is enhanced with a `response_mime_type` of `"application/json"` and, if a `json_schema` is provided, it is included in the request payload.

Support for json_response in ChatModels.ChatGoogleAI

---

lib/chat_models/chat_ollama_ai.ex
test/chat_models/chat_ollama_ai_test.exs

I noticed that https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-chat-completion and https://github.com/ollama/ollama/blob/main/docs/modelfile.md#valid-parameters-and-values document that those options all need to be passed to the `options: {}` sub structure.
My local instance testing with llama `v3.1` and ollama `v0.3.10` complains because `num_gqa` is unknown. I left it in there for now because other models might need it.

Fix options being passed to the ollama chat api

---

lib/chat_models/chat_open_ai.ex
test/chat_models/chat_open_ai_test.exs

When creating a `ContentPart`, now determine how the file is handled based on `opts[:type]`.
For backward compatibility, the default value of `opts[:type]` is set to `:base64`.

Support for file with file_id in ChatOpenAI

---

README.md
lib/chains/llm_chain.ex
lib/chat_models/chat_anthropic.ex
lib/chat_models/chat_bumblebee.ex
lib/chat_models/chat_google_ai.ex
lib/chat_models/chat_mistral_ai.ex
lib/chat_models/chat_ollama_ai.ex
lib/chat_models/chat_open_ai.ex
lib/chat_models/chat_perplexity.ex
lib/chat_models/chat_vertex_ai.ex
lib/message_processors/json_processor.ex
lib/telemetry.ex
test/chat_models/telemetry_test.exs
test/test_helper.exs

This is an attempt to add some basic telemetry. This will be useful to then create an OTEL package to automatically get tracing from this telemetry setup. 
I am happy to add tests as well but the setup is currently difficult in this project to run outside of CI. Is that the intent to not be able to run them locally? Is there way to make them run locally?

adds telemetry

---

lib/chat_models/chat_vertex_ai.ex
test/chat_models/chat_vertex_ai_test.exs

Vertex AI supports file url and can work with any file url compared to google ai which only  support file url uploaded using its files api, google ai support was added recently and most of the ground work is already there in https://github.com/brainlid/langchain/pull/286  to support file _url for content part in vertex .

vertex ai file url support

---

lib/chat_models/chat_google_ai.ex
lib/chat_models/chat_mistral_ai.ex
lib/chat_models/chat_ollama_ai.ex
lib/chat_models/chat_open_ai.ex
lib/chat_models/chat_perplexity.ex
lib/chat_models/chat_vertex_ai.ex
test/chat_models/chat_mistral_ai_test.exs
test/chat_models/chat_ollama_ai_test.exs
test/chat_models/chat_perplexity_test.exs
test/chat_models/chat_vertex_ai_test.exs

After the migration to ContentPart-based message content, 19 tests were failing because chat models weren't properly handling the new ContentPart list format. Models expected strings but received ContentPart structures.
- Added missing ContentPart handling in ChatOllamaAI, ChatMistralAI, ChatPerplexity, ChatOpenAI, ChatVertexAI, and ChatGoogleAI
- Added extract_content_text/1 helpers to convert ContentPart lists back to strings where needed
- Fixed system message handling in ChatVertexAI and ChatGoogleAI to extract text from ContentPart structures
- Updated test expectations to use ContentPart.text!() format instead of plain strings
- Fixed role mapping in ChatVertexAI to use atoms consistently
All tests should pass now ✅

Fix ContentPart migration

---

lib/chat_models/chat_mistral_ai.ex
test/chat_models/chat_mistral_ai_test.exs

The `ChatMistralAI` module does not have  support for Mistral's structured output feature yet.
- **New fields**: `json_response` (boolean) and `json_schema` (map)
- **Response formats**: Support for both `json_object` (free-form) and `json_schema` (strict validation)
**With JSON Schema:**
```elixir
chat = ChatMistralAI.new!(%{
model: "ministral-8b-latest",
json_response: true,
json_schema: %{
"type" => "json_schema",
"json_schema" => %{
"schema" => %{"properties" => %{"name" => %{"type" => "string"}}},
"name" => "output",
"strict" => true
}
}
})
```
**Free-form JSON:**
```elixir
chat = ChatMistralAI.new!(%{
model: "ministral-8b-latest",
json_response: true
})
```

feat: Add structured output support to ChatMistralAI 

---

lib/text_splitter.ex
lib/text_splitter/character_text_splitter.ex
lib/text_splitter/recursive_character_text_splitter.ex
test/text_splitter_test.exs

The text splitters (CharacterTextSplitter and RecursiveCharacterTextSplitter) currently use character count (String.length/1) for determining chunk sizes. This is good but in most cases we would like to use tokenizers that mimic what llms use (for example https://github.com/openai/tiktoken), so it would be good to pass custom tokenizer function instead.
- Added a configurable tokenizer field to both text splitter modules:
- Backward Compatible: Default tokenizer remains &String.length/1
Example usage:
```
word_tokenizer = fn text -> text |> String.split() |> length() end
splitter = CharacterTextSplitter.new!(%{
chunk_size: 50,  # 50 words instead of characters
tokenizer: word_tokenizer
})
```
should resolve https://github.com/brainlid/langchain/issues/311

feat: add configurable tokenizer to text splitters

---

lib/utils/bedrock_stream_decoder.ex
test/utils/bedrock_stream_decoder_test.exs

When there are multiple messages in the buffer (`remaining != ""`), they're added to the list of chunks with `[chunk | chunks]`. That list wasn't being reversed before being returned, which results in incorrect output like `[" there are a", "Yes", "few concerning"]`.

Fix AWS Bedrock stream decoder ordering issue

---

mix.exs

The change to gettext's setup in https://github.com/brainlid/langchain/pull/271 requires 0.26 or higher, so we should reflect this in mix.exs.
Note that this will expose projects using langchain to the same warning fixed in that PR.
Context: https://hexdocs.pm/gettext/changelog.html#v0-26-0

fix: Require gettext ~> 0.26

---

lib/chat_models/chat_open_ai.ex
test/chat_models/chat_open_ai_test.exs

Add support for organization ID as a parameter in the OpenAI chat model. This allows users to specify the organization context when making requests, enabling better management of resources and access control within the OpenAI API.
The change includes updates to the `ChatOpenAI` module and its tests to ensure the organization ID is correctly passed and utilized in API calls.

feat: Add organization ID as a parameter

---

lib/chat_models/chat_ollama_ai.ex
test/chat_models/chat_ollama_ai_test.exs

ChatOllamaAI was missing the `verbose_api` field that exists in all other chat models (OpenAI, Anthropic, GoogleAI, VertexAI). This caused streaming to fail with a `KeyError` when the streaming utilities tried to access `model.verbose_api`.
- Added `verbose_api` field to ChatOllamaAI struct with `default: false`
- Included in `@create_fields` for proper initialization
- Added to `serialize_config` for persistence
- Added comprehensive test coverage
- ✅ All existing tests pass
- ✅ New tests added for `verbose_api` functionality
- ✅ Verified streaming now works without errors
- ✅ Tested ContentParts v0.4.x compatibility confirmed
- `lib/chat_models/chat_ollama_ai.ex`: Added verbose_api field and configuration
- `test/chat_models/chat_ollama_ai_test.exs`: Added tests for verbose_api
This …

Add missing verbose_api field to ChatOllamaAI for streaming compatibility

---

CHANGELOG.md
lib/chat_models/chat_ollama_ai.ex
test/chat_models/chat_ollama_ai_test.exs

Fixes the `stop` field in `ChatOllamaAI` to match Ollama API requirements by changing type from `:string` to `{:array, :string}`. This resolves a critical bug where stop sequences were completely non-functional due to API type mismatch.
The original implementation used `field :stop, :string`, but Ollama API requires stop sequences as arrays and rejects strings with the error: `{"error":"option \"stop\" must be of type array"}`. This made the stop sequences feature completely
unusable.
- **Changed field type**: `:string` → `{:array, :string}, default: []`
- **Added smart filtering**: Empty arrays are excluded from API requests via `Utils.conditionally_add_to_map` to preserve modelfile defaults (prevents overriding built-in stop tokens like `<|eot_id|>`)
- **Updated API conversion**: …

Fix ChatOllamaAI stop sequences: change from string to array type

---

lib/chat_models/chat_google_ai.ex
test/chat_models/chat_google_ai_test.exs

This PR resolves crash in `for_api/1` when `ToolResult` content is a string.
The original bug caused the following error during the process of converting the API request input to json.
```
** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for type LangChain.Message.ContentPart (a struct), Jason.Encoder protocol must always be explicitly implemented.
```

Prevent crash when ToolResult with string in ChatGoogleAI.for_api/1

---

lib/chat_models/chat_ollama_ai.ex
lib/chat_models/chat_open_ai.ex

- fixes an Ollama compiler warning and callback issue

only include "user" with OpenAI request when a value is provided

---

lib/images/generated_image.ex
lib/images/open_ai_image.ex

This PR adds support for gpt-image-1 in LangChain.Images.OpenAIImage, enabling image generation using OpenAI’s latest model.
- Added support for the gpt-image-1 model.
- Introduced an optional output_format attribute for more flexible image outputs.
- Fixed a bug where the style attribute caused API request errors (this parameter is not valid for dall-e-2).
- gpt-image-1 is now the recommended model for image generation.
- The fix ensures smoother compatibility across different OpenAI image models.

Adds support for gpt-image-1 in LangChain.Images.OpenAIImage

---

lib/chains/llm_chain.ex
test/chains/llm_chain_test.exs

As suggested by @brainlid at https://github.com/brainlid/langchain/pull/343.
This adds a new `should_continue?` option for `mode: :step` that provides a cleaner way to manage the execution loop by implementing conditional. Read the mentioned PR for better explanation of the use case.
Added a new use case and update the `mode: :step` use case to highlight when to use it solo.
- Internally handles the loop logic for stepped execution
- Allows fine-grained control of the `run/2` loop when no chain modification is required
- Streamlines scenarios like max iterations, error thresholds and guardrails.
```elixir
should_continue_fn = fn chain ->
chain.needs_response && length(chain.exchanged_messages) < 10
end
{:ok, final_chain} = LLMChain.run(chain, mode: :step, should_continue?: …
```

Adds should_continue? optional function to mode step

---

lib/chat_models/chat_open_ai.ex
test/chat_models/chat_open_ai_test.exs

I couldn't find an escape hatch that would allow me to pass `parallel_tool_calls: false` to the OpenAI API endpoint, so naturally here's a PR adding an explicit support for it!

Add `parallel_tool_calls` option to `ChatOpenAI` model

---

lib/utils/bedrock_config.ex
test/support/bedrock_helpers.ex
test/test_helper.exs
test/utils/bedrock_config_test.exs

This change allows for improved handling of AWS credentials, accommodating scenarios where a session token may be required (e.g. when use credentials given by AWS Sts)
- Introduced a new private function `maybe_add_token/1` to conditionally add the AWS session token to the credentials if it is available in the application environment.
- Updated the credentials retrieval logic to incorporate this new functionality, enhancing the flexibility of AWS credential management.

Add optional AWS session token handling in BedrockHelpers

---

lib/chat_models/chat_open_ai.ex

Add `req_config` field to `ChatModels.ChatOpenAI` to support custom HTTP request configuration options.

Add req_config to ChatModels.ChatOpenAI

---

lib/chat_models/chat_google_ai.ex
lib/token_usage.ex

When streaming with ChatGoogleAI, empirically, Google returns the *cumulative* token usage with each delta - unlike other models that return only the incremental token usage. Thus we need to avoid adding together the delta's token usages, instead just taking the last one.
I noticed this by comparing usage stats to those reported in [Helicone](https://www.helicone.ai/) for the same requests. With this PR, they match exactly.

fix(ChatGoogleAI): Handle cumulative token usage

---

lib/chat_models/chat_google_ai.ex

If you enable thought summaries for ChatGoogleAI (using https://github.com/brainlid/langchain/pull/354) and then send a follow-up message, the :thinking content parts cause a "no function clause matching" error in `for_api`. This PR adds an empty case and some `List.flatten` calls to filter it out of the resulting lists.
(The :thinking parts are only thought summaries and are not meant to be included in future generation requests; see https://ai.google.dev/gemini-api/docs/thinking#summaries. There is a separate way to include thinking in future generation requests, [thought signatures](https://ai.google.dev/gemini-api/docs/thinking#signatures), but it is more complicated and only used alongside function calling.)
Error stack trace:
```
[error] ** (FunctionClauseError) no function clause …
```

fix(ChatGoogleAI): Prevent error from thinking content parts

---

lib/chat_models/chat_open_ai.ex
test/chat_models/chat_open_ai_test.exs

GPT-5 has a new `verbosity` parameter: https://platform.openai.com/docs/api-reference/chat/create#chat-create-verbosity
This PR adds support for optionally passing it in (defaults to `nil`)

Support verbosity parameter for ChatOpenAI

---

lib/chat_models/chat_open_ai_responses.ex
lib/chat_models/reasoning_options.ex
lib/message/tool_call.ex
lib/utils.ex
test/chat_models/chat_anthropic_test.exs
test/chat_models/chat_open_ai_responses_test.exs
test/chat_models/responses_openai_azure_live_api_test.exs

This is the continuation of the https://github.com/brainlid/langchain/pull/318 PR with the help of @arjan fixing tool-calling and adding reasoning support.
I verified it works on Azure by running `test/chat_models/responses_openai_azure_live_api_test.exs` as well as manually testing with Teacherspace (dayjob)
Notes:
spec for PR verification:
```
Adding support for the OpenAI Responses API with tool-calling  and Azure support.
OpenAI released a new Responses API, this new API has significant differences to the previous chat API we supported in `lib/chat_models/chat_open_ai.ex`, to add support for this new API we created a new module in `lib/chat_models/chat_open_ai_responses.ex`.
So far the new module works for simple responses however it has not been thoroughly tested and there seem to be …
```

OpenAI responses

---

lib/chat_models/chat_bumblebee.ex

When LangChain is used as a dependency in a project that does not include an optional dependencies like Nx, it would emit warnings but that don't really apply

Suppress the compiler warning messages for ChatBumblebee

---

lib/chat_models/chat_open_ai_responses.ex
test/chat_models/chat_open_ai_responses_test.exs
test/chat_models/responses_openai_azure_live_api_test.exs

Noticed that we had a small bug in OpenAI responses API for json-schema format.
**https://platform.openai.com/docs/guides/structured-outputs#structured-outputs-vs-json-mode**
Tested via automated tests connected to Azure (below) + manually in Teacherspace were we used structured schemas already.
Note: OpenAI now requires these prompts to contain *JSON* in the description.
So for example a prompt like: `"Analyze #{text} and measure it's helpfulness, accuracy and weirdness"` needs to be changed so something `"Analyze #{text} and measure it's helpfulness, accuracy and weirdness as JSON"`

fix: Support for json-schema in OpenAI responses API
